-- Авто-генерация D1-схемы из src/shared/config/registry (единый источник правды).
-- Не редактировать вручную: правьте реестр и запустите "npm run gen:d1".
-- Версионность протокола (docs/ru/schema-evolution.md §4): таблица registry_versions
-- и колонки patients/phases.registry_version генерируются в baseline.
-- Отдельной миграции нет — эволюция схемы только через ресет БД (npm run db:restart).

CREATE TABLE registry_versions (
    "version" INTEGER PRIMARY KEY,
    "effective_at" TEXT NOT NULL,
    "note" TEXT NOT NULL,
    "approved_by" TEXT
);

CREATE TABLE patients (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "study_entry_date" TEXT NULL,
    "birth_year" INTEGER NULL,
    "gender" INTEGER NULL,
    "education_level" INTEGER NULL,
    "career_level" INTEGER NULL,
    "living_status" INTEGER NULL,
    "disability_status" INTEGER NULL,
    "family_history" INTEGER NULL,
    "personality_type" INTEGER NULL,
    "consent_version" TEXT NULL,
    "consent_date" TEXT NULL,
    "consent_withdrawn_at" TEXT NULL,
    "registry_version" INTEGER NOT NULL DEFAULT 1 REFERENCES registry_versions(version),
    CHECK ("birth_year" >= 1900)
);

CREATE TABLE phases (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "patient_id" INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    "phase_order_id" INTEGER NOT NULL,
    "phase_relative_id" INTEGER NULL,
    "phase_start_date" TEXT NULL,
    "phase_duration_months" REAL NULL,
    "intermission_duration" REAL NULL,
    "subdepression_const" INTEGER NULL,
    "affective_lability_rem" INTEGER NULL,
    "anxiety_lability_rem" INTEGER NULL,
    "unfavorable_env" INTEGER NULL,
    "pain_in_remission" INTEGER NULL,
    "treatment_in_remission" INTEGER NULL,
    "prophylaxis_type" INTEGER NULL,
    "onset_trigger" INTEGER NULL,
    "main_component" INTEGER NULL,
    "depression_severity" INTEGER NULL,
    "orientation" INTEGER NULL,
    "melancholy_obj" INTEGER NULL,
    "anxiety_obj" INTEGER NULL,
    "apathy_obj" INTEGER NULL,
    "sleep_worsening" INTEGER NULL,
    "appetite_loss" INTEGER NULL,
    "cognitive_impair" INTEGER NULL,
    "physical_pain" INTEGER NULL,
    "fatigue" INTEGER NULL,
    "fixed_posture" INTEGER NULL,
    "mimic_poverty" INTEGER NULL,
    "monotonous_voice" INTEGER NULL,
    "motor_retardation" INTEGER NULL,
    "delayed_response" INTEGER NULL,
    "restlessness" INTEGER NULL,
    "affect_lability" INTEGER NULL,
    "motor_agitation" INTEGER NULL,
    "hygiene_decline" INTEGER NULL,
    "diurnal_rhythm" INTEGER NULL,
    "hypochondria" INTEGER NULL,
    "hallucinations" INTEGER NULL,
    "delusions" INTEGER NULL,
    "obsessions" INTEGER NULL,
    "insight" INTEGER NULL,
    "beta_blockers" INTEGER NULL,
    "ca_blockers" INTEGER NULL,
    "other_depressogenic" INTEGER NULL,
    "vitamins" INTEGER NULL,
    "vascular_drugs" INTEGER NULL,
    "nootropics" INTEGER NULL,
    "mood_stabilizers" INTEGER NULL,
    "ad_tricyclic" INTEGER NULL,
    "ad_tetracyclic" INTEGER NULL,
    "ad_other_noradr" INTEGER NULL,
    "ad_serotonergic" INTEGER NULL,
    "ad_snri" INTEGER NULL,
    "ad_maoi" INTEGER NULL,
    "ad_atypical_mech" INTEGER NULL,
    "ad_transitional" INTEGER NULL,
    "ad_dose_level" INTEGER NULL,
    "ad_route" INTEGER NULL,
    "days_to_improvement" INTEGER NULL,
    "total_days" INTEGER NULL,
    "ad_efficacy" INTEGER NULL,
    "ad_switch" INTEGER NULL,
    "switch_reason" INTEGER NULL,
    "nl_typical" INTEGER NULL,
    "nl_atypical" INTEGER NULL,
    "nl_dose_level" INTEGER NULL,
    "trank_benzodiazep" INTEGER NULL,
    "trank_barbiturates" INTEGER NULL,
    "trank_other_chem" INTEGER NULL,
    "trank_herbal" INTEGER NULL,
    "hypnotics" INTEGER NULL,
    "trank_dose_level" INTEGER NULL,
    "trank_route" INTEGER NULL,
    "trank_efficacy" INTEGER NULL,
    "hamd_total" INTEGER NULL,
    "beck_total" INTEGER NULL,
    "clock_drawing_test" INTEGER NULL,
    "mmse_total" INTEGER NULL,
    "registry_version" INTEGER NOT NULL DEFAULT 1 REFERENCES registry_versions(version),
    UNIQUE ("patient_id", "phase_order_id")
);

INSERT INTO registry_versions (version, effective_at, note) VALUES (1, date('now'), 'Baseline v1: исходный набор CRF');
